sudo: required
language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - python setup.py test
# command to run tests
script:
  - pytest
branches:
  only:
    - master