sudo: required
language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
before_install:
  - cp config.yml
# command to install dependencies
install:
  - python setup.py -q test
# command to run tests
script:
  - pytest
branches:
  only:
    - master