sudo: required
language: python
python:
  - "2.7"
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
  - "3.7"
# command to install dependencies
install:
  - sudo pip install requests
  - python setup.py -q install
# command to run tests
script:
  - pytest
branches:
  only:
    - master
    - 0.1.0